apiVersion: v1
kind: Service
metadata:
  name: outyet-service
  namespace: new-demo
spec:
  type: NodePort
  selector:
    app: outyet
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8081
      nodePort: 30081
